#!/usr/bin/env zsh

# remove docker container if it exists
docker rm -f dom_xss_4

# remove image if it exists
docker rmi -f dom_xss_4

# build image 
docker build -t dom_xss_4 .

# create container
docker run -it -d -p 8082:80 --name=dom_xss_4 --rm dom_xss_4